// <auto-generated />
using System;
using GemBidScraper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GemBidScraper.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260729041618_FixStringTruncationAndMaxLengths")]
    partial class FixStringTruncationAndMaxLengths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GemBidScraper.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BOQTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BidDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BidEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BidNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BidOpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BidType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BidValidityDays")
                        .HasColumnType("int");

                    b.Property<string>("ConsigneeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsigneeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliveryDays")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EMDAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EMDRequired")
                        .HasColumnType("bit");

                    b.Property<decimal?>("EPBGPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("EPBGRequired")
                        .HasColumnType("bit");

                    b.Property<string>("EvaluationMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrievanceEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InspectionRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MIIPreference")
                        .HasColumnType("bit");

                    b.Property<bool>("MSEPreference")
                        .HasColumnType("bit");

                    b.Property<string>("Ministry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTimeline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdfUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryProductCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScrapedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("GemBidScraper.Models.GeMBidExtract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdvisoryBank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArbitrationClause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutoCRACDays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BOQDetailDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BOQTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BidDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BidEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BidNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("BidOpeningDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("BidToRAEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("BidValidityDays")
                        .HasColumnType("int");

                    b.Property<string>("BuyerSpecificationDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CardEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CardItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardMinistry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CardQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CardStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CategoryKey")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CategorySubKey")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ConsigneeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsigneeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsigneeQuantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactDetailsOfGrievanceRedressal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocumentRequiredFromSeller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EPBGDurationMonths")
                        .HasColumnType("int");

                    b.Property<decimal?>("EPBGPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EmdAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EstimatedBidValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EvaluationMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinancialDocumentRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeMARPTSSearchedResults")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeMARPTSSearchedStrings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ITCAvailableToBuyer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectionAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("InspectionByBuyerOwnAgency")
                        .HasColumnType("bit");

                    b.Property<bool?>("InspectionRequired")
                        .HasColumnType("bit");

                    b.Property<string>("InspectionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JsonData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MIICompliance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("MIIPurchasePreference")
                        .HasColumnType("bit");

                    b.Property<bool?>("MSEPurchasePreference")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaximumPurchasePreferencePercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MediationClause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinimumAverageAnnualTurnover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MinimumNumberOfBidsRequiredToDisableAutomaticBidExtension")
                        .HasColumnType("int");

                    b.Property<string>("Ministry")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("NumberOfAutoExtensionCount")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfDaysForWhichBidWouldBeAutoExtended")
                        .HasColumnType("int");

                    b.Property<string>("OEMAverageTurnover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganisationName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PastExperienceRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PastPerformance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTimelines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicalCharacteristics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryProductCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PurchasePreferencePercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RAQualificationRule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelevantCategoriesSelectedForNotification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Required")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceInclusions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceRequirement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SimilarCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificationDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificationParameterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surface")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalSpecificationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<string>("TrainingModule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfBid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Values")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarrantyText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearsOfPastExperienceRequired")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BidEndDateTime");

                    b.HasIndex("BidNumber")
                        .IsUnique()
                        .HasFilter("[BidNumber] IS NOT NULL");

                    b.HasIndex("CategoryKey");

                    b.HasIndex("CategorySubKey");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DepartmentName");

                    b.HasIndex("EmdAmount");

                    b.HasIndex("Ministry");

                    b.HasIndex("OrganisationName");

                    b.HasIndex("BidEndDateTime", "CreatedOn");

                    b.ToTable("gembidextracts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
