// <auto-generated />
using System;
using GemBidScraper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GemBidScraper.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260714192312_GeMBid")]
    partial class GeMBid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GemBidScraper.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BOQTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BidDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BidEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BidNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BidOpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BidType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BidValidityDays")
                        .HasColumnType("int");

                    b.Property<string>("ConsigneeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsigneeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliveryDays")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EMDAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EMDRequired")
                        .HasColumnType("bit");

                    b.Property<decimal?>("EPBGPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("EPBGRequired")
                        .HasColumnType("bit");

                    b.Property<string>("EvaluationMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrievanceEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InspectionRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MIIPreference")
                        .HasColumnType("bit");

                    b.Property<bool>("MSEPreference")
                        .HasColumnType("bit");

                    b.Property<string>("Ministry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTimeline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdfUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryProductCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScrapedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("GemBidScraper.Models.GeMBid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BOQTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BidCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BidDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BidEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BidNature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BidNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BidOpeningDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BidReferenceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BidTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BidValidityDays")
                        .HasColumnType("int");

                    b.Property<string>("BidVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandAllowed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerPincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificationRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClarificationEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClarificationStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConsigneeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConsigneeDeliveryDays")
                        .HasColumnType("int");

                    b.Property<string>("ConsigneeItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsigneeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConsigneeQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("ConsigneeSerialNo")
                        .HasColumnType("int");

                    b.Property<string>("ContactDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeliveryDays")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryPincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DocumentDownloadEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DocumentDownloadStart")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EMDAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EMDPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("EMDRequired")
                        .HasColumnType("bit");

                    b.Property<decimal?>("EPBGPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("EPBGRequired")
                        .HasColumnType("bit");

                    b.Property<string>("EligibilityCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EvaluationMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("GeMSellerRequired")
                        .HasColumnType("bit");

                    b.Property<string>("GrievanceEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guarantee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HSNCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectionAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("InspectionRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LocalContentPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("MIIPreference")
                        .HasColumnType("bit");

                    b.Property<bool?>("MSEPreference")
                        .HasColumnType("bit");

                    b.Property<bool?>("MSMEAllowed")
                        .HasColumnType("bit");

                    b.Property<bool?>("MakeInIndiaPreference")
                        .HasColumnType("bit");

                    b.Property<string>("Ministry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("NSICAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("OEMAuthorization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTimeline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdfUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PreBidMeeting")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PreBidMeetingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreBidMeetingVenue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryProductCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductSubType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchKeywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("StartupAllowed")
                        .HasColumnType("bit");

                    b.Property<bool?>("StartupPreference")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TenderFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("TenderFeeRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<string>("TurnoverCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfBid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Warranty")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GeMBids");
                });
#pragma warning restore 612, 618
        }
    }
}
